chacha.S:7:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
chacha.S:10:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
chacha.S:11:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
chacha.S:12:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:14:1: error: instruction requires: Not 64-bit mode
pushl $1
^
chacha.S:15:1: error: instruction requires: Not 64-bit mode
popl %ecx
^
<instantiation>:7:31: error: invalid operand for instruction
 leaq chacha_constants(%rip), %edx
                              ^~~~
chacha.S:21:1: note: while in macro instantiation
LOAD_VAR_PIC chacha_constants, %edx
^
chacha.S:903:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:904:1: error: instruction requires: Not 64-bit mode
popl %edi
^
chacha.S:905:1: error: instruction requires: Not 64-bit mode
popl %esi
^
chacha.S:907:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
<instantiation>:7:31: error: invalid operand for instruction
 leaq chacha_constants(%rip), %eax
                              ^~~~
chacha.S:1258:1: note: while in macro instantiation
LOAD_VAR_PIC chacha_constants, %eax
^
chacha.S:1316:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
chacha.S:1317:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:1337:1: error: instruction requires: Not 64-bit mode
pushl 28(%ebp)
^
chacha.S:1338:1: error: instruction requires: Not 64-bit mode
pushl 24(%ebp)
^
chacha.S:1339:1: error: instruction requires: Not 64-bit mode
pushl 20(%ebp)
^
chacha.S:1340:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:1347:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:1348:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
chacha.S:1353:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
chacha.S:1354:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:1359:1: error: instruction requires: Not 64-bit mode
pushl 32(%ebp)
^
chacha.S:1360:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:1361:1: error: instruction requires: Not 64-bit mode
pushl 16(%ebp)
^
chacha.S:1362:1: error: instruction requires: Not 64-bit mode
pushl 12(%ebp)
^
chacha.S:1374:1: error: instruction requires: Not 64-bit mode
pushl 28(%ebp)
^
chacha.S:1375:1: error: instruction requires: Not 64-bit mode
pushl 24(%ebp)
^
chacha.S:1376:1: error: instruction requires: Not 64-bit mode
pushl 20(%ebp)
^
chacha.S:1377:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:1384:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:1385:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
