poly1305.S:12:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:15:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:16:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:17:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:38:1: error: instruction requires: Not 64-bit mode
pushl 8(%ebp)
^
poly1305.S:39:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:40:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:42:1: error: instruction requires: Not 64-bit mode
pushl %eax
^
poly1305.S:46:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:47:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:48:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:50:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:56:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:57:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:58:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:59:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:185:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:186:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:187:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:188:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:198:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:199:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:200:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:769:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:770:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:771:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:895:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:896:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:897:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:906:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:907:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:908:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:909:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:1159:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:1160:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:1161:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:1162:1: error: instruction requires: Not 64-bit mode
popl %esi
^
