chacha.S:7:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
chacha.S:10:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
chacha.S:11:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
chacha.S:12:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
<instantiation>:7:31: error: invalid operand for instruction
 leaq chacha_constants(%rip), %eax
                              ^~~~
chacha.S:14:1: note: while in macro instantiation
LOAD_VAR_PIC chacha_constants, %eax
^
chacha.S:534:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:535:1: error: instruction requires: Not 64-bit mode
popl %edi
^
chacha.S:536:1: error: instruction requires: Not 64-bit mode
popl %esi
^
chacha.S:538:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
chacha.S:688:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:689:1: error: instruction requires: Not 64-bit mode
popl %edi
^
chacha.S:690:1: error: instruction requires: Not 64-bit mode
popl %esi
^
chacha.S:692:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
<instantiation>:7:31: error: invalid operand for instruction
 leaq chacha_constants(%rip), %eax
                              ^~~~
chacha.S:718:1: note: while in macro instantiation
LOAD_VAR_PIC chacha_constants, %eax
^
chacha.S:776:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
chacha.S:777:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:797:1: error: instruction requires: Not 64-bit mode
pushl 28(%ebp)
^
chacha.S:798:1: error: instruction requires: Not 64-bit mode
pushl 24(%ebp)
^
chacha.S:799:1: error: instruction requires: Not 64-bit mode
pushl 20(%ebp)
^
chacha.S:800:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:807:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:808:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
chacha.S:813:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
chacha.S:814:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:819:1: error: instruction requires: Not 64-bit mode
pushl 32(%ebp)
^
chacha.S:820:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:821:1: error: instruction requires: Not 64-bit mode
pushl 16(%ebp)
^
chacha.S:822:1: error: instruction requires: Not 64-bit mode
pushl 12(%ebp)
^
chacha.S:834:1: error: instruction requires: Not 64-bit mode
pushl 28(%ebp)
^
chacha.S:835:1: error: instruction requires: Not 64-bit mode
pushl 24(%ebp)
^
chacha.S:836:1: error: instruction requires: Not 64-bit mode
pushl 20(%ebp)
^
chacha.S:837:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
chacha.S:844:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
chacha.S:845:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
