poly1305.S:12:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:15:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:16:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:17:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:21:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:22:1: error: instruction requires: Not 64-bit mode
pushl 20(%ebp)
^
poly1305.S:23:1: error: instruction requires: Not 64-bit mode
pushl %eax
^
poly1305.S:32:1: error: instruction requires: Not 64-bit mode
pushl %edx
^
poly1305.S:33:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:35:1: error: instruction requires: Not 64-bit mode
pushl %eax
^
poly1305.S:43:1: error: instruction requires: Not 64-bit mode
pushl 8(%ebp)
^
poly1305.S:44:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:45:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:47:1: error: instruction requires: Not 64-bit mode
pushl %eax
^
poly1305.S:51:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:52:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:53:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:55:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:61:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:62:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:63:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:64:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:126:1: error: instruction requires: Not 64-bit mode
pushl $32
^
poly1305.S:129:1: error: instruction requires: Not 64-bit mode
pushl %eax
^
poly1305.S:130:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:151:1: error: instruction requires: Not 64-bit mode
pushl $32
^
poly1305.S:152:1: error: instruction requires: Not 64-bit mode
pushl $0
^
poly1305.S:153:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:193:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:194:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:195:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:196:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:202:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:203:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:204:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:691:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:692:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:693:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:810:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:811:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:812:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:819:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:820:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:821:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:822:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:1069:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:1070:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:1071:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:1072:1: error: instruction requires: Not 64-bit mode
popl %esi
^
