poly1305.S:13:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:16:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:17:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:18:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:36:1: error: instruction requires: Not 64-bit mode
pushl 8(%ebp)
^
poly1305.S:37:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:38:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:40:1: error: instruction requires: Not 64-bit mode
pushl %eax
^
poly1305.S:43:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:44:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:45:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:47:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:54:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:57:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:58:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:59:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:245:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:246:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:247:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:249:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:260:1: error: instruction requires: Not 64-bit mode
pushl %ebp
^
poly1305.S:263:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:264:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:265:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:742:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:743:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:744:1: error: instruction requires: Not 64-bit mode
popl %esi
^
poly1305.S:746:1: error: instruction requires: Not 64-bit mode
popl %ebp
^
poly1305.S:756:1: error: instruction requires: Not 64-bit mode
pushl %esi
^
poly1305.S:757:1: error: instruction requires: Not 64-bit mode
pushl %edi
^
poly1305.S:758:1: error: instruction requires: Not 64-bit mode
pushl %ebx
^
poly1305.S:1035:1: error: instruction requires: Not 64-bit mode
popl %ebx
^
poly1305.S:1036:1: error: instruction requires: Not 64-bit mode
popl %edi
^
poly1305.S:1037:1: error: instruction requires: Not 64-bit mode
popl %esi
^
